# YAML Pipeline for Creating a Bicep file with Resource Group, App Service Plan, and Web App

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: ps-rule-assert@2
  displayName: Analyze Azure template file
  continueOnError: true
  inputs:
    modules: 'PSRule.Rules.Azure'
    inputPath: 'Template/'
    outputPath: reports/ps-rule-results.json


- task: AzureCLI@2
  inputs:
    azureSubscription: 'Lab-Connection-2'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment group create --resource-group lab-rg1 --template-file Template/WebApp.bicep 
    failOnStandardError: true
    displayName: 'Deploy Bicep file'
