# YAML Pipeline for Creating a Bicep file with Resource Group, App Service Plan, and Web App

trigger:
- main

variables:
  rgName: 'lab-rg1'
  appPlanName: 'app-plan-$(rgName)'
  webAppName: 'app-$(rgName)'
  location: 'northeurope'
 
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: ps-rule-assert@2
  displayName: Analyze Azure template file
  continueOnError: true
  inputs:
    modules: 'PSRule.Rules.Azure'
    inputPath: 'Template/'
    outputPath: reports/ps-rule-results.json


- task: AzureCLI@2
  inputs:
    azureSubscription: 'Lab-Connection-2'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az group create --name $(rgName) --location $(location)
      az deployment group create --resource-group "Lab-Pipeline-Yavor" --template-file Template/WebApp.bicep --parameters rgName=$(rgName) location=$(location) appServicePlanName=$(appPlanName) appServiceAppName=$(webAppName)
    failOnStandardError: true
    displayName: 'Deploy Bicep file'
